name: CI

on:
  push:
    branches: [cicd]
  pull_request:
    branches: [cicd]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install all dependencies
        run: npm run install-all

      - name: Run unit tests
        run: cd client && npm test -- --watchAll=false

      - name: Build
        run: npm run build
